package feeper.entity;
// Generated Feb 1, 2014 9:45:43 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CodigoFonte generated by hbm2java
 */
public class CodigoFonte  implements java.io.Serializable {


     private Integer id;
     private int idAutor;
     private byte[] fonte;
     private byte[] fonteAnterior;
     private Date dataCadastro;
     private Date dataAlteracao;
     private int idStatus;
     private boolean ativo;

    public CodigoFonte() {
    }

	
    public CodigoFonte(int idAutor, byte[] fonte, Date dataCadastro, int idStatus, boolean ativo) {
        this.idAutor = idAutor;
        this.fonte = fonte;
        this.dataCadastro = dataCadastro;
        this.idStatus = idStatus;
        this.ativo = ativo;
    }
    public CodigoFonte(int idAutor, byte[] fonte, byte[] fonteAnterior, Date dataCadastro, Date dataAlteracao, int idStatus, boolean ativo) {
       this.idAutor = idAutor;
       this.fonte = fonte;
       this.fonteAnterior = fonteAnterior;
       this.dataCadastro = dataCadastro;
       this.dataAlteracao = dataAlteracao;
       this.idStatus = idStatus;
       this.ativo = ativo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdAutor() {
        return this.idAutor;
    }
    
    public void setIdAutor(int idAutor) {
        this.idAutor = idAutor;
    }
    public byte[] getFonte() {
        return this.fonte;
    }
    
    public void setFonte(byte[] fonte) {
        this.fonte = fonte;
    }
    public byte[] getFonteAnterior() {
        return this.fonteAnterior;
    }
    
    public void setFonteAnterior(byte[] fonteAnterior) {
        this.fonteAnterior = fonteAnterior;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Date getDataAlteracao() {
        return this.dataAlteracao;
    }
    
    public void setDataAlteracao(Date dataAlteracao) {
        this.dataAlteracao = dataAlteracao;
    }
    public int getIdStatus() {
        return this.idStatus;
    }
    
    public void setIdStatus(int idStatus) {
        this.idStatus = idStatus;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }




}


