package feeper.entity;
// Generated Feb 1, 2014 9:45:43 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CodigoFonteMarcacao generated by hbm2java
 */
public class CodigoFonteMarcacao  implements java.io.Serializable {


     private Integer id;
     private int idCodigoFonte;
     private int idAutor;
     private int idTipoMarcacao;
     private int linhaInicio;
     private int linhaFim;
     private String anotacao;
     private Date dataCadastro;
     private boolean ativo;
     private Long idNovidade;

    public CodigoFonteMarcacao() {
    }

	
    public CodigoFonteMarcacao(int idCodigoFonte, int idAutor, int idTipoMarcacao, int linhaInicio, int linhaFim, String anotacao, Date dataCadastro, boolean ativo) {
        this.idCodigoFonte = idCodigoFonte;
        this.idAutor = idAutor;
        this.idTipoMarcacao = idTipoMarcacao;
        this.linhaInicio = linhaInicio;
        this.linhaFim = linhaFim;
        this.anotacao = anotacao;
        this.dataCadastro = dataCadastro;
        this.ativo = ativo;
    }
    public CodigoFonteMarcacao(int idCodigoFonte, int idAutor, int idTipoMarcacao, int linhaInicio, int linhaFim, String anotacao, Date dataCadastro, boolean ativo, Long idNovidade) {
       this.idCodigoFonte = idCodigoFonte;
       this.idAutor = idAutor;
       this.idTipoMarcacao = idTipoMarcacao;
       this.linhaInicio = linhaInicio;
       this.linhaFim = linhaFim;
       this.anotacao = anotacao;
       this.dataCadastro = dataCadastro;
       this.ativo = ativo;
       this.idNovidade = idNovidade;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdCodigoFonte() {
        return this.idCodigoFonte;
    }
    
    public void setIdCodigoFonte(int idCodigoFonte) {
        this.idCodigoFonte = idCodigoFonte;
    }
    public int getIdAutor() {
        return this.idAutor;
    }
    
    public void setIdAutor(int idAutor) {
        this.idAutor = idAutor;
    }
    public int getIdTipoMarcacao() {
        return this.idTipoMarcacao;
    }
    
    public void setIdTipoMarcacao(int idTipoMarcacao) {
        this.idTipoMarcacao = idTipoMarcacao;
    }
    public int getLinhaInicio() {
        return this.linhaInicio;
    }
    
    public void setLinhaInicio(int linhaInicio) {
        this.linhaInicio = linhaInicio;
    }
    public int getLinhaFim() {
        return this.linhaFim;
    }
    
    public void setLinhaFim(int linhaFim) {
        this.linhaFim = linhaFim;
    }
    public String getAnotacao() {
        return this.anotacao;
    }
    
    public void setAnotacao(String anotacao) {
        this.anotacao = anotacao;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
    public Long getIdNovidade() {
        return this.idNovidade;
    }
    
    public void setIdNovidade(Long idNovidade) {
        this.idNovidade = idNovidade;
    }




}


