package feeper.entity;
// Generated Feb 8, 2014 11:15:29 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CodigoFonteResultado generated by hbm2java
 */
public class CodigoFonteResultado  implements java.io.Serializable {


     private Integer id;
     private int idCodigoFonte;
     private int idStatus;
     private String mensagem;
     private Date dataCadastro;

    public CodigoFonteResultado() {
    }

	
    public CodigoFonteResultado(int idCodigoFonte, int idStatus, Date dataCadastro) {
        this.idCodigoFonte = idCodigoFonte;
        this.idStatus = idStatus;
        this.dataCadastro = dataCadastro;
    }
    public CodigoFonteResultado(int idCodigoFonte, int idStatus, String mensagem, Date dataCadastro) {
       this.idCodigoFonte = idCodigoFonte;
       this.idStatus = idStatus;
       this.mensagem = mensagem;
       this.dataCadastro = dataCadastro;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdCodigoFonte() {
        return this.idCodigoFonte;
    }
    
    public void setIdCodigoFonte(int idCodigoFonte) {
        this.idCodigoFonte = idCodigoFonte;
    }
    public int getIdStatus() {
        return this.idStatus;
    }
    
    public void setIdStatus(int idStatus) {
        this.idStatus = idStatus;
    }
    public String getMensagem() {
        return this.mensagem;
    }
    
    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }




}


