package feeper.entity;
// Generated Jan 28, 2014 7:18:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Conquista generated by hbm2java
 */
public class Conquista  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private int pontosParaConquista;
     private int pontosIncremento;
     private String formula;
     private Date dataCadastro;
     private boolean ativo;

    public Conquista() {
    }

    public Conquista(String nome, int pontosParaConquista, int pontosIncremento, String formula, Date dataCadastro, boolean ativo) {
       this.nome = nome;
       this.pontosParaConquista = pontosParaConquista;
       this.pontosIncremento = pontosIncremento;
       this.formula = formula;
       this.dataCadastro = dataCadastro;
       this.ativo = ativo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public int getPontosParaConquista() {
        return this.pontosParaConquista;
    }
    
    public void setPontosParaConquista(int pontosParaConquista) {
        this.pontosParaConquista = pontosParaConquista;
    }
    public int getPontosIncremento() {
        return this.pontosIncremento;
    }
    
    public void setPontosIncremento(int pontosIncremento) {
        this.pontosIncremento = pontosIncremento;
    }
    public String getFormula() {
        return this.formula;
    }
    
    public void setFormula(String formula) {
        this.formula = formula;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }




}


