package feeper.entity;
// Generated Feb 1, 2014 9:45:43 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.List;


/**
 * Exercicio generated by hbm2java
 */
public class Exercicio  implements java.io.Serializable {


    private Integer id;
    private String nome;
    private byte[] descricao;
    private int idAutor;
    private Date dataCadastro;
    private boolean ativo;
    private String descricaoHtml;
    private Pessoa autor;
    private List<ExercicioValidacao> validacoes;


    public Exercicio() {
    }

	
    public Exercicio(String nome, int idAutor, Date dataCadastro, boolean ativo) {
        this.nome = nome;
        this.idAutor = idAutor;
        this.dataCadastro = dataCadastro;
        this.ativo = ativo;
    }
    public Exercicio(String nome, byte[] descricao, int idAutor, Date dataCadastro, boolean ativo, String descricaoHtml) {
       this.nome = nome;
       this.descricao = descricao;
       this.idAutor = idAutor;
       this.dataCadastro = dataCadastro;
       this.ativo = ativo;
       this.descricaoHtml = descricaoHtml;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public byte[] getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(byte[] descricao) {
        this.descricao = descricao;
    }
    public int getIdAutor() {
        return this.idAutor;
    }
    
    public void setIdAutor(int idAutor) {
        this.idAutor = idAutor;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
    
    public String getDescricaoHtml() {
        return this.descricaoHtml;
    }
    
    public void setDescricaoHtml(String descricaoHtml) {
        this.descricaoHtml = descricaoHtml;
    }

    public Pessoa getAutor() {
        return autor;
    }

    public void setAutor(Pessoa autor) {
        this.autor = autor;
    }

    public List<ExercicioValidacao> getValidacoes() {
        return validacoes;
    }

    public void setValidacoes(List<ExercicioValidacao> validacoes) {
        this.validacoes = validacoes;
    }




}


