package feeper.entity;
// Generated Feb 1, 2014 9:45:43 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ExercicioValidacao generated by hbm2java
 */
public class ExercicioValidacao  implements java.io.Serializable {


     private Integer id;
     private int idExercicio;
     private String entrada;
     private String saida;
     private String mensagem;
     private Date dataCadastro;
     private boolean ativo;

    public ExercicioValidacao() {
    }

	
    public ExercicioValidacao(int idExercicio, String entrada, String saida, Date dataCadastro, boolean ativo) {
        this.idExercicio = idExercicio;
        this.entrada = entrada;
        this.saida = saida;
        this.dataCadastro = dataCadastro;
        this.ativo = ativo;
    }
    public ExercicioValidacao(int idExercicio, String entrada, String saida, String mensagem, Date dataCadastro, boolean ativo) {
       this.idExercicio = idExercicio;
       this.entrada = entrada;
       this.saida = saida;
       this.mensagem = mensagem;
       this.dataCadastro = dataCadastro;
       this.ativo = ativo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdExercicio() {
        return this.idExercicio;
    }
    
    public void setIdExercicio(int idExercicio) {
        this.idExercicio = idExercicio;
    }
    public String getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(String entrada) {
        this.entrada = entrada;
    }
    public String getSaida() {
        return this.saida;
    }
    
    public void setSaida(String saida) {
        this.saida = saida;
    }
    public String getMensagem() {
        return this.mensagem;
    }
    
    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }




}


