package feeper.entity;
// Generated Jan 27, 2014 10:21:02 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Exercicio generated by hbm2java
 */
public class Exercicio  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private byte[] descricao;
     private int idAutor;
     private Date dataCadastro;
     private boolean ativo;
     private int idNivelDificuldade;

    public Exercicio() {
    }

	
    public Exercicio(String nome, int idAutor, Date dataCadastro, boolean ativo, int idNivelDificuldade) {
        this.nome = nome;
        this.idAutor = idAutor;
        this.dataCadastro = dataCadastro;
        this.ativo = ativo;
        this.idNivelDificuldade = idNivelDificuldade;
    }
    public Exercicio(String nome, byte[] descricao, int idAutor, Date dataCadastro, boolean ativo, int idNivelDificuldade) {
       this.nome = nome;
       this.descricao = descricao;
       this.idAutor = idAutor;
       this.dataCadastro = dataCadastro;
       this.ativo = ativo;
       this.idNivelDificuldade = idNivelDificuldade;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public byte[] getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(byte[] descricao) {
        this.descricao = descricao;
    }
    public int getIdAutor() {
        return this.idAutor;
    }
    
    public void setIdAutor(int idAutor) {
        this.idAutor = idAutor;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
    public int getIdNivelDificuldade() {
        return this.idNivelDificuldade;
    }
    
    public void setIdNivelDificuldade(int idNivelDificuldade) {
        this.idNivelDificuldade = idNivelDificuldade;
    }




}


