package feeper.entity;
// Generated Feb 1, 2014 9:45:43 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Grade generated by hbm2java
 */
public class Grade  implements java.io.Serializable {


     private Integer id;
     private int idTurma;
     private int idAluno;
     private int idExercicio;
     private BigDecimal nota;
     private boolean visivel;

    public Grade() {
    }

    public Grade(int idTurma, int idAluno, int idExercicio, BigDecimal nota, boolean visivel) {
       this.idTurma = idTurma;
       this.idAluno = idAluno;
       this.idExercicio = idExercicio;
       this.nota = nota;
       this.visivel = visivel;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdTurma() {
        return this.idTurma;
    }
    
    public void setIdTurma(int idTurma) {
        this.idTurma = idTurma;
    }
    public int getIdAluno() {
        return this.idAluno;
    }
    
    public void setIdAluno(int idAluno) {
        this.idAluno = idAluno;
    }
    public int getIdExercicio() {
        return this.idExercicio;
    }
    
    public void setIdExercicio(int idExercicio) {
        this.idExercicio = idExercicio;
    }
    public BigDecimal getNota() {
        return this.nota;
    }
    
    public void setNota(BigDecimal nota) {
        this.nota = nota;
    }
    public boolean isVisivel() {
        return this.visivel;
    }
    
    public void setVisivel(boolean visivel) {
        this.visivel = visivel;
    }




}


