package feeper.entity;
// Generated Jan 6, 2014 9:05:50 PM by Hibernate Tools 3.2.1.GA


import flexjson.JSON;
import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


    private Long id;
    private int idPessoa;
    private String mensagem;
    private int idTipoLog;
    private Date dataCadastro;

    public Log() {
    }

    public Log(int idPessoa, String mensagem, int idTipoLog, Date dataCadastro) {
       this.idPessoa = idPessoa;
       this.mensagem = mensagem;
       this.idTipoLog = idTipoLog;
       this.dataCadastro = dataCadastro;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public int getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(int idPessoa) {
        this.idPessoa = idPessoa;
    }
    
    public String getMensagem() {
        return this.mensagem;
    }
    
    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }
    public int getIdTipoLog() {
        return this.idTipoLog;
    }
    
    public void setIdTipoLog(int idTipoLog) {
        this.idTipoLog = idTipoLog;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }




}


