package feeper.entity;
// Generated Jan 28, 2014 7:18:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * MensagemComentario generated by hbm2java
 */
public class MensagemComentario  implements java.io.Serializable {


     private Long id;
     private long idMensagemCabecalho;
     private int idAutor;
     private Date dataCadastro;
     private boolean ativo;

    public MensagemComentario() {
    }

    public MensagemComentario(long idMensagemCabecalho, int idAutor, Date dataCadastro, boolean ativo) {
       this.idMensagemCabecalho = idMensagemCabecalho;
       this.idAutor = idAutor;
       this.dataCadastro = dataCadastro;
       this.ativo = ativo;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getIdMensagemCabecalho() {
        return this.idMensagemCabecalho;
    }
    
    public void setIdMensagemCabecalho(long idMensagemCabecalho) {
        this.idMensagemCabecalho = idMensagemCabecalho;
    }
    public int getIdAutor() {
        return this.idAutor;
    }
    
    public void setIdAutor(int idAutor) {
        this.idAutor = idAutor;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }




}


