package feeper.entity;
// Generated Jan 28, 2014 7:18:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Mensagem generated by hbm2java
 */
public class Mensagem  implements java.io.Serializable {


     private Long id;
     private long idMensagemCabecalho;
     private int idPessoa;
     private String texto;
     private Date dataCadastro;
     private boolean ativo;

    public Mensagem() {
    }

    public Mensagem(long idMensagemCabecalho, int idPessoa, String texto, Date dataCadastro, boolean ativo) {
       this.idMensagemCabecalho = idMensagemCabecalho;
       this.idPessoa = idPessoa;
       this.texto = texto;
       this.dataCadastro = dataCadastro;
       this.ativo = ativo;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getIdMensagemCabecalho() {
        return this.idMensagemCabecalho;
    }
    
    public void setIdMensagemCabecalho(long idMensagemCabecalho) {
        this.idMensagemCabecalho = idMensagemCabecalho;
    }
    public int getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(int idPessoa) {
        this.idPessoa = idPessoa;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }




}


