package feeper.entity;
// Generated Feb 1, 2014 9:45:43 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * MensagemLeitor generated by hbm2java
 */
public class MensagemLeitor  implements java.io.Serializable {


     private Long id;
     private long idMensagemCabecalho;
     private int idLeitor;
     private char tipoLeitor;
     private Date dataUltimaLeitura;
     private boolean ativo;

    public MensagemLeitor() {
    }

    public MensagemLeitor(long idMensagemCabecalho, int idLeitor, char tipoLeitor, Date dataUltimaLeitura, boolean ativo) {
       this.idMensagemCabecalho = idMensagemCabecalho;
       this.idLeitor = idLeitor;
       this.tipoLeitor = tipoLeitor;
       this.dataUltimaLeitura = dataUltimaLeitura;
       this.ativo = ativo;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getIdMensagemCabecalho() {
        return this.idMensagemCabecalho;
    }
    
    public void setIdMensagemCabecalho(long idMensagemCabecalho) {
        this.idMensagemCabecalho = idMensagemCabecalho;
    }
    public int getIdLeitor() {
        return this.idLeitor;
    }
    
    public void setIdLeitor(int idLeitor) {
        this.idLeitor = idLeitor;
    }
    public char getTipoLeitor() {
        return this.tipoLeitor;
    }
    
    public void setTipoLeitor(char tipoLeitor) {
        this.tipoLeitor = tipoLeitor;
    }
    public Date getDataUltimaLeitura() {
        return this.dataUltimaLeitura;
    }
    
    public void setDataUltimaLeitura(Date dataUltimaLeitura) {
        this.dataUltimaLeitura = dataUltimaLeitura;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }




}


