package feeper.entity;
// Generated Jan 28, 2014 7:18:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Novidade generated by hbm2java
 */
public class Novidade  implements java.io.Serializable {


     private Long id;
     private int idTipoNovidade;
     private String resumo;
     private Date dataCadastro;
     private Date dataLeitura;
     private Integer idDestinatario;
     private boolean publico;

    public Novidade() {
    }

	
    public Novidade(int idTipoNovidade, Date dataCadastro, boolean publico) {
        this.idTipoNovidade = idTipoNovidade;
        this.dataCadastro = dataCadastro;
        this.publico = publico;
    }
    public Novidade(int idTipoNovidade, String resumo, Date dataCadastro, Date dataLeitura, Integer idDestinatario, boolean publico) {
       this.idTipoNovidade = idTipoNovidade;
       this.resumo = resumo;
       this.dataCadastro = dataCadastro;
       this.dataLeitura = dataLeitura;
       this.idDestinatario = idDestinatario;
       this.publico = publico;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public int getIdTipoNovidade() {
        return this.idTipoNovidade;
    }
    
    public void setIdTipoNovidade(int idTipoNovidade) {
        this.idTipoNovidade = idTipoNovidade;
    }
    public String getResumo() {
        return this.resumo;
    }
    
    public void setResumo(String resumo) {
        this.resumo = resumo;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Date getDataLeitura() {
        return this.dataLeitura;
    }
    
    public void setDataLeitura(Date dataLeitura) {
        this.dataLeitura = dataLeitura;
    }
    public Integer getIdDestinatario() {
        return this.idDestinatario;
    }
    
    public void setIdDestinatario(Integer idDestinatario) {
        this.idDestinatario = idDestinatario;
    }
    public boolean isPublico() {
        return this.publico;
    }
    
    public void setPublico(boolean publico) {
        this.publico = publico;
    }




}


