package feeper.entity;
// Generated Jan 6, 2014 9:05:50 PM by Hibernate Tools 3.2.1.GA


import feeper.model.HibernateUtil;
import java.util.Date;
import java.util.List;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String email;
     private String senha;
     private Date dataCadastro;
     private Date dataUltimoAcesso;
     private char tipoPessoa;
     private boolean ativo;
     private String ip;
     private int idNivelDificuldade;

    public Pessoa() {
    }

	
    public Pessoa(String nome, String email, String senha, Date dataCadastro, char tipoPessoa, boolean ativo, int idNivelDificuldade) {
        this.nome = nome;
        this.email = email;
        this.senha = senha;
        this.dataCadastro = dataCadastro;
        this.tipoPessoa = tipoPessoa;
        this.ativo = ativo;
        this.idNivelDificuldade = idNivelDificuldade;
    }
    public Pessoa(String nome, String email, String senha, Date dataCadastro, Date dataUltimoAcesso, char tipoPessoa, boolean ativo, String ip, int idNivelDificuldade) {
       this.nome = nome;
       this.email = email;
       this.senha = senha;
       this.dataCadastro = dataCadastro;
       this.dataUltimoAcesso = dataUltimoAcesso;
       this.tipoPessoa = tipoPessoa;
       this.ativo = ativo;
       this.ip = ip;
       this.idNivelDificuldade = idNivelDificuldade;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Date getDataUltimoAcesso() {
        return this.dataUltimoAcesso;
    }
    
    public void setDataUltimoAcesso(Date dataUltimoAcesso) {
        this.dataUltimoAcesso = dataUltimoAcesso;
    }
    public char getTipoPessoa() {
        return this.tipoPessoa;
    }
    
    public void setTipoPessoa(char tipoPessoa) {
        this.tipoPessoa = tipoPessoa;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public int getIdNivelDificuldade() {
        return this.idNivelDificuldade;
    }
    
    public void setIdNivelDificuldade(int idNivelDificuldade) {
        this.idNivelDificuldade = idNivelDificuldade;
    }

//    public void TesteConsulta(){
//        executeHQLQuery("from Pessoa p where p.id = 1");
//    }
//    
//    private void executeHQLQuery(String hql) {
//        try {
//            Session session = HibernateUtil.getSessionFactory().openSession();
//            session.beginTransaction();
//            Query q = session.createQuery(hql);
//            List resultList = q.list();
//            //displayResult(resultList);
//            session.getTransaction().commit();
//        } catch (HibernateException he) {
//            he.printStackTrace();
//        }
//    }

}


