package feeper.entity;
// Generated Feb 1, 2014 9:45:43 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.List;


/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


    private Integer id;
    private String nome;
    private String email;
    private String senha;
    private Date dataCadastro;
    private Date dataUltimoAcesso;
    private boolean ativo;
    private boolean possuiFoto;
    private int idNivelDificuldade;
    private int idPerfil;
    private List<Turma> turmas;
    //private List<Turma> turmasProfessor;


    public Pessoa() {
    }

	
    public Pessoa(String nome, String email, String senha, Date dataCadastro, boolean ativo, int idNivelDificuldade) {
        this.nome = nome;
        this.email = email;
        this.senha = senha;
        this.dataCadastro = dataCadastro;
        this.ativo = ativo;
        this.idNivelDificuldade = idNivelDificuldade;
    }
    public Pessoa(String nome, String email, String senha, Date dataCadastro, Date dataUltimoAcesso, boolean ativo, int idNivelDificuldade) {
       this.nome = nome;
       this.email = email;
       this.senha = senha;
       this.dataCadastro = dataCadastro;
       this.dataUltimoAcesso = dataUltimoAcesso;
       this.ativo = ativo;
       this.idNivelDificuldade = idNivelDificuldade;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Date getDataUltimoAcesso() {
        return this.dataUltimoAcesso;
    }
    
    public void setDataUltimoAcesso(Date dataUltimoAcesso) {
        this.dataUltimoAcesso = dataUltimoAcesso;
    }

    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
    public int getIdNivelDificuldade() {
        return this.idNivelDificuldade;
    }
    
    public void setIdNivelDificuldade(int idNivelDificuldade) {
        this.idNivelDificuldade = idNivelDificuldade;
    }

    public List<Turma> getTurmas() {
        return turmas;
    }

    public void setTurmas(List<Turma> turmas) {
        this.turmas = turmas;
    }

    public int getIdPerfil() {
        return idPerfil;
    }

    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }

    public boolean isPossuiFoto() {
        return possuiFoto;
    }

    public void setPossuiFoto(boolean possuiFoto) {
        this.possuiFoto = possuiFoto;
    }


}


