package feeper.entity;
// Generated Feb 8, 2014 11:15:29 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Resposta generated by hbm2java
 */
public class Resposta  implements java.io.Serializable {


     private Integer id;
     private int idExercicio;
     private int idAutor;
     private int idStatus;
     private Date dataCadastro;
     private String mensagem;

    public Resposta() {
    }

	
    public Resposta(int idExercicio, int idStatus, Date dataCadastro) {
        this.idExercicio = idExercicio;
        this.idStatus = idStatus;
        this.dataCadastro = dataCadastro;
    }
    public Resposta(int idExercicio, int idStatus, String mensagem, Date dataCadastro) {
       this.idExercicio = idExercicio;
       this.idStatus = idStatus;
       this.mensagem = mensagem;
       this.dataCadastro = dataCadastro;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getIdExercicio() {
        return idExercicio;
    }

    public void setIdExercicio(int idExercicio) {
        this.idExercicio = idExercicio;
    }

    public int getIdAutor() {
        return idAutor;
    }

    public void setIdAutor(int idAutor) {
        this.idAutor = idAutor;
    }

    public int getIdStatus() {
        return idStatus;
    }

    public void setIdStatus(int idStatus) {
        this.idStatus = idStatus;
    }

    public Date getDataCadastro() {
        return dataCadastro;
    }

    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }

    public String getMensagem() {
        return mensagem;
    }

    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }
   
    

}


