package feeper.entity;
// Generated Jan 27, 2014 10:21:02 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * StatusCodigoFonte generated by hbm2java
 */
public class StatusCodigoFonte  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Date dataCadastro;
     private boolean ativo;

    public StatusCodigoFonte() {
    }

    public StatusCodigoFonte(String nome, Date dataCadastro, boolean ativo) {
       this.nome = nome;
       this.dataCadastro = dataCadastro;
       this.ativo = ativo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }




}


