package feeper.entity;
// Generated Jan 27, 2014 10:21:02 PM by Hibernate Tools 3.2.1.GA



/**
 * TipoLog generated by hbm2java
 */
public class TipoLog  implements java.io.Serializable {


     private Integer id;
     private String nome;

    public TipoLog() {
    }

    public TipoLog(String nome) {
       this.nome = nome;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


