package feeper.entity;
// Generated Jan 28, 2014 7:18:55 PM by Hibernate Tools 3.2.1.GA



/**
 * TurmaPessoa generated by hbm2java
 */
public class TurmaPessoa  implements java.io.Serializable {


     private TurmaPessoaId id;

    public TurmaPessoa() {
    }

    public TurmaPessoa(TurmaPessoaId id) {
       this.id = id;
    }
   
    public TurmaPessoaId getId() {
        return this.id;
    }
    
    public void setId(TurmaPessoaId id) {
        this.id = id;
    }




}


