package feeper.entity;
// Generated Jan 27, 2014 10:21:02 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Turma generated by hbm2java
 */
public class Turma  implements java.io.Serializable {

     private Integer id;
     private String nome;
     private Date dataCadastro;
     private Date dataEncerramento;
     private boolean ativo;
     private Integer idProfessor;
     private Pessoa professor;

    public Turma() {
    }

	
    public Turma(String nome, Date dataCadastro, boolean ativo) {
        this.nome = nome;
        this.dataCadastro = dataCadastro;
        this.ativo = ativo;
    }
    public Turma(String nome, Date dataCadastro, Date dataEncerramento, boolean ativo, Pessoa professor) {
       this.nome = nome;
       this.dataCadastro = dataCadastro;
       this.dataEncerramento = dataEncerramento;
       this.ativo = ativo;
       this.professor = professor;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Date getDataEncerramento() {
        return this.dataEncerramento;
    }
    
    public void setDataEncerramento(Date dataEncerramento) {
        this.dataEncerramento = dataEncerramento;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
    public Integer getIdProfessor() {
        return this.idProfessor;
    }
    
    public void setIdProfessor(Integer idProfessor) {
        this.idProfessor = idProfessor;
    }
    public Pessoa getProfessor() {
        return this.professor;
    }
    
    public void setProfessor(Pessoa professor) {
        this.professor = professor;
    }

}


