package feeper.entity;
// Generated Jan 27, 2014 10:21:02 PM by Hibernate Tools 3.2.1.GA



/**
 * TurmaExercicio generated by hbm2java
 */
public class TurmaExercicio  implements java.io.Serializable {


     private TurmaExercicioId id;
     private boolean visivel;

    public TurmaExercicio() {
    }

    public TurmaExercicio(TurmaExercicioId id, boolean visivel) {
       this.id = id;
       this.visivel = visivel;
    }
   
    public TurmaExercicioId getId() {
        return this.id;
    }
    
    public void setId(TurmaExercicioId id) {
        this.id = id;
    }
    public boolean isVisivel() {
        return this.visivel;
    }
    
    public void setVisivel(boolean visivel) {
        this.visivel = visivel;
    }




}


