package feeper.entity;
// Generated Feb 1, 2014 9:45:43 AM by Hibernate Tools 3.2.1.GA



/**
 * TurmaExercicioId generated by hbm2java
 */
public class TurmaExercicioId  implements java.io.Serializable {


     private int idTurma;
     private int idExercicio;

    public TurmaExercicioId() {
    }

    public TurmaExercicioId(int idTurma, int idExercicio) {
       this.idTurma = idTurma;
       this.idExercicio = idExercicio;
    }
   
    public int getIdTurma() {
        return this.idTurma;
    }
    
    public void setIdTurma(int idTurma) {
        this.idTurma = idTurma;
    }
    public int getIdExercicio() {
        return this.idExercicio;
    }
    
    public void setIdExercicio(int idExercicio) {
        this.idExercicio = idExercicio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TurmaExercicioId) ) return false;
		 TurmaExercicioId castOther = ( TurmaExercicioId ) other; 
         
		 return (this.getIdTurma()==castOther.getIdTurma())
 && (this.getIdExercicio()==castOther.getIdExercicio());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTurma();
         result = 37 * result + this.getIdExercicio();
         return result;
   }   


}


