package feeper.Data.entity;
// Generated Feb 1, 2014 9:45:43 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CodigoFonte generated by hbm2java
 */
public class CodigoFonte  implements java.io.Serializable {


     private Integer id;
     private int idAutor;
     private String fonte;
     private String fonteAnterior;
     private Date dataCadastro;
     private boolean principal;
     private int idExercicio;
     private String classe;
     private Pessoa autor;
     private Exercicio exercicio;

    public CodigoFonte() {
    }

	
    public CodigoFonte(int idAutor, String fonte, Date dataCadastro, int idExercicio, boolean principal) {
        this.idAutor = idAutor;
        this.fonte = fonte;
        this.dataCadastro = dataCadastro;
        this.principal = principal;
        this.idExercicio = idExercicio;
    }
    public CodigoFonte(int idAutor, String fonte, String fonteAnterior, Date dataCadastro, int idExercicio, boolean principal) {
       this.idAutor = idAutor;
       this.fonte = fonte;
       this.fonteAnterior = fonteAnterior;
       this.dataCadastro = dataCadastro;
       this.idExercicio = idExercicio;
       this.principal = principal;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getIdAutor() {
        return idAutor;
    }

    public void setIdAutor(int idAutor) {
        this.idAutor = idAutor;
    }

    public String getFonte() {
        return fonte;
    }

    public void setFonte(String fonte) {
        this.fonte = fonte;
    }

    public String getFonteAnterior() {
        return fonteAnterior;
    }

    public void setFonteAnterior(String fonteAnterior) {
        this.fonteAnterior = fonteAnterior;
    }

    public Date getDataCadastro() {
        return dataCadastro;
    }

    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }

    public boolean isPrincipal() {
        return principal;
    }

    public void setPrincipal(boolean principal) {
        this.principal = principal;
    }

    public int getIdExercicio() {
        return idExercicio;
    }

    public void setIdExercicio(int idExercicio) {
        this.idExercicio = idExercicio;
    }

    public Pessoa getAutor() {
        return autor;
    }

    public void setAutor(Pessoa autor) {
        this.autor = autor;
    }

    public Exercicio getExercicio() {
        return exercicio;
    }

    public void setExercicio(Exercicio exercicio) {
        this.exercicio = exercicio;
    }

    public String getClasse() {
        return classe;
    }

    public void setClasse(String classe) {
        this.classe = classe;
    }
   
    




}


