package feeper.Data.entity;


/**
 * Exercicio generated by hbm2java
 */
public class ExercicioPontos implements java.io.Serializable {

    private Integer id;
    private int idAluno;
    private int idExercicio;
    private int pontos;
    
    
    public ExercicioPontos() {
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setIdAluno(int idAluno) {
        this.idAluno = idAluno;
    }

    public void setIdExercicio(int idExercicio) {
        this.idExercicio = idExercicio;
    }

    public void setPontos(int pontos) {
        this.pontos = pontos;
    }

    public Integer getId() {
        return id;
    }

    public int getIdAluno() {
        return idAluno;
    }

    public int getIdExercicio() {
        return idExercicio;
    }

    public int getPontos() {
        return pontos;
    }


}
