package feeper.Data.entity;
// Generated Feb 1, 2014 9:45:43 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ExercicioClasseMarcacao generated by hbm2java
 */
public class ExercicioClasseMarcacao  implements java.io.Serializable {


     private Integer id;
     private int idExercicioClasse;
     private int idAutor;
     private int idTipoMarcacao;
     private int linhaInicio;
     private int linhaFim;
     private String anotacao;
     private Date dataCadastro;
     private boolean ativo;
     private Long idNovidade;

    public ExercicioClasseMarcacao() {
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public int getIdExercicioClasse() {
        return idExercicioClasse;
    }

    public void setIdExercicioClasse(int idExercicioClasse) {
        this.idExercicioClasse = idExercicioClasse;
    }

    public int getIdAutor() {
        return this.idAutor;
    }
    
    public void setIdAutor(int idAutor) {
        this.idAutor = idAutor;
    }
    public int getIdTipoMarcacao() {
        return this.idTipoMarcacao;
    }
    
    public void setIdTipoMarcacao(int idTipoMarcacao) {
        this.idTipoMarcacao = idTipoMarcacao;
    }
    public int getLinhaInicio() {
        return this.linhaInicio;
    }
    
    public void setLinhaInicio(int linhaInicio) {
        this.linhaInicio = linhaInicio;
    }
    public int getLinhaFim() {
        return this.linhaFim;
    }
    
    public void setLinhaFim(int linhaFim) {
        this.linhaFim = linhaFim;
    }
    public String getAnotacao() {
        return this.anotacao;
    }
    
    public void setAnotacao(String anotacao) {
        this.anotacao = anotacao;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
    public Long getIdNovidade() {
        return this.idNovidade;
    }
    
    public void setIdNovidade(Long idNovidade) {
        this.idNovidade = idNovidade;
    }
}


