package feeper.Data.entity;
// Generated Feb 1, 2014 9:45:43 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ExercicioValidacao generated by hbm2java
 */
public class ExercicioClasseValidacao  implements java.io.Serializable {


     private Integer id;
     private int idExercicio;
     private String fonte;
     private String saida;
     private String mensagemCompilacao;
     private String mensagem;
     private Date dataCadastro;
     private boolean ativo;
     private Integer ordem;

    public ExercicioClasseValidacao() {
    }

	
    public ExercicioClasseValidacao(int idExercicio, String fonte, String saida, Date dataCadastro, boolean ativo) {
        this.idExercicio = idExercicio;
        this.fonte = fonte;
        this.saida = saida;
        this.dataCadastro = dataCadastro;
        this.ativo = ativo;
    }
    public ExercicioClasseValidacao(int idExercicio, String fonte, String saida, String mensagem, Date dataCadastro, boolean ativo) {
       this.idExercicio = idExercicio;
       this.fonte = fonte;
       this.saida = saida;
       this.mensagem = mensagem;
       this.dataCadastro = dataCadastro;
       this.ativo = ativo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdExercicio() {
        return this.idExercicio;
    }
    
    public void setIdExercicio(int idExercicio) {
        this.idExercicio = idExercicio;
    }
    public String getSaida() {
        return this.saida;
    }
    
    public void setSaida(String saida) {
        this.saida = saida;
    }
    public String getMensagem() {
        return this.mensagem;
    }
    
    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }

    public String getFonte() {
        return this.fonte;
    }
    
    public void setFonte(String fonte) {
        this.fonte = fonte;
    }
    public String getMensagemCompilacao() {
        return this.mensagemCompilacao;
    }
    
    public void setMensagemCompilacao(String mensagemCompilacao) {
        this.mensagemCompilacao = mensagemCompilacao;
    }
    public Integer getOrdem() {
        return this.ordem;
    }
    
    public void setOrdem(Integer ordem) {
        this.ordem = ordem;
    }

}


