package feeper.Data.entity;
// Generated Feb 1, 2014 9:45:43 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.List;

/**
 * Exercicio generated by hbm2java
 */
public class Exercicio implements java.io.Serializable {

    private Integer id;
    private String nome;
    private int idAutor;
    private Date dataCadastro;
    private boolean ativo;
    private boolean usaDescricaoPDF;
    private String descricaoHtml;
    private byte[] descricao;
    private Pessoa autor;
    private List<ExercicioCasoTeste> casosTeste;
    private ExercicioInterface interfaceSolucao;
    
    private int idUploadTemp;

    public Exercicio() {
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public int getIdAutor() {
        return this.idAutor;
    }

    public void setIdAutor(int idAutor) {
        this.idAutor = idAutor;
    }

    public Date getDataCadastro() {
        return this.dataCadastro;
    }

    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }

    public boolean isAtivo() {
        return this.ativo;
    }

    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }

    public boolean getUsaDescricaoPDF() {
        return usaDescricaoPDF;
    }

    public void setUsaDescricaoPDF(boolean usaDescricaoPDF) {
        this.usaDescricaoPDF = usaDescricaoPDF;
    }

    public String getDescricaoHtml() {
        return this.descricaoHtml;
    }

    public void setDescricaoHtml(String descricaoHtml) {
        this.descricaoHtml = descricaoHtml;
    }
    
    public byte[] getDescricao() {
        return this.descricao;
    }

    public void setDescricao(byte[] descricao) {
        this.descricao = descricao;
    }

    public Pessoa getAutor() {
        return autor;
    }

    public void setAutor(Pessoa autor) {
        this.autor = autor;
    }

    public List<ExercicioCasoTeste> getCasosTeste() {
        return casosTeste;
    }

    public void setCasosTeste(List<ExercicioCasoTeste> casosTeste) {
        this.casosTeste = casosTeste;
    }

    public ExercicioInterface getInterfaceSolucao() {
        return interfaceSolucao;
    }

    public void setInterfaceSolucao(ExercicioInterface interfaceSolucao) {
        this.interfaceSolucao = interfaceSolucao;
    }

    public int getIdUploadTemp() {
        return idUploadTemp;
    }

    public void setIdUploadTemp(int idUploadTemp) {
        this.idUploadTemp = idUploadTemp;
    }

    
}
