package feeper.Data.entity;


/**
 * Exercicio generated by hbm2java

 */
public class Medalha {
    
    //Niveis 
    public static Integer NIVEL_BRONZE = 1;    // Representa o Ganho de 1 medalha
    public static Integer NIVEL_PRATA = 2;     // Representa o Ganho de 2 medalhas
    public static Integer NIVEL_OURO = 3;      // Representa o Ganho de 3 medalhas
    
    //Medalhas
    public static Integer LOGIN = 1;
    public static Integer EXERCICIOS_CONCLUIDOS = 2;
    public static Integer EXERCICIOS_ENVIADOS = 3;
    public static Integer EXERCICIOS_SEM_ERROS = 4;
    public static Integer ATIVIDADE_DIARIA = 5;  // verificar melhor forma de implementar 
    public static Integer PONTUACAO_OBTIDA = 6; 
    public static Integer RANKING_MELHOR_DA_TURMA = 7; 
    public static Integer RANKING_MELHOR_DO_FEEPER = 8; 
    
    private Integer id;
    private String nome;
    private String descricao;

    public Medalha(Integer id, String nome, String descricao) {
        this.id = id;
        this.nome = nome;
        this.descricao = descricao;
    }
    
    public Medalha(){
        
    }

    public Integer getId() {
        return id;
    }

    public String getNome() {
        return nome;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    
    
    
   

    
    
    
}
