package feeper.Data.entity;


/**
 * Exercicio generated by hbm2java

 */
public class MedalhaPessoa implements java.io.Serializable {
    
    private Integer id;
    private Integer idMedalha;
    private Integer idPessoa;
    private Integer nivel;

    public void setMedalha(Medalha medalha) {
        this.medalha = medalha;
    }

    public Medalha getMedalha() {
        return medalha;
    }
    
    private Medalha medalha;

    public MedalhaPessoa() {
    }

    public MedalhaPessoa(Integer idMedalha, Integer idPessoa, Integer nivel) {
        this.idMedalha = idMedalha;
        this.idPessoa = idPessoa;
        this.nivel = nivel;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIdMedalha() {
        return idMedalha;
    }

    public void setIdMedalha(Integer idMedalha) {
        this.idMedalha = idMedalha;
    }

    public Integer getIdPessoa() {
        return idPessoa;
    }

    public void setIdPessoa(Integer idPessoa) {
        this.idPessoa = idPessoa;
    }

    public Integer getNivel() {
        return nivel;
    }

    public void setNivel(Integer nivel) {
        this.nivel = nivel;
    }
    
}
