package feeper.Data.entity;
// Generated Feb 1, 2014 9:45:43 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * MensagemCurtir generated by hbm2java
 */
public class MensagemCurtir  implements java.io.Serializable {


     private Long id;
     private Long idMensagemCabecalho;
     private Long idMensagemComentario;
     private int idAutor;
     private Date dataCadastro;
     private boolean ativo;

    public MensagemCurtir() {
    }

	
    public MensagemCurtir(int idAutor, Date dataCadastro, boolean ativo) {
        this.idAutor = idAutor;
        this.dataCadastro = dataCadastro;
        this.ativo = ativo;
    }
    public MensagemCurtir(Long idMensagemCabecalho, Long idMensagemComentario, int idAutor, Date dataCadastro, boolean ativo) {
       this.idMensagemCabecalho = idMensagemCabecalho;
       this.idMensagemComentario = idMensagemComentario;
       this.idAutor = idAutor;
       this.dataCadastro = dataCadastro;
       this.ativo = ativo;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Long getIdMensagemCabecalho() {
        return this.idMensagemCabecalho;
    }
    
    public void setIdMensagemCabecalho(Long idMensagemCabecalho) {
        this.idMensagemCabecalho = idMensagemCabecalho;
    }
    public Long getIdMensagemComentario() {
        return this.idMensagemComentario;
    }
    
    public void setIdMensagemComentario(Long idMensagemComentario) {
        this.idMensagemComentario = idMensagemComentario;
    }
    public int getIdAutor() {
        return this.idAutor;
    }
    
    public void setIdAutor(int idAutor) {
        this.idAutor = idAutor;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }




}


