package feeper.Data.entity;
// Generated Feb 1, 2014 9:45:43 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * MensagemCabecalho generated by hbm2java
 */
public class MensagemCabecalho implements java.io.Serializable {

    private Long id;
    private Integer idExercicioClasseMarcacao;
    private Integer idExercicioSolucaoClasseMarcacao;
    private boolean publico;
    private Date dataCadastro;
    private boolean ativo;

    public MensagemCabecalho() {
    }

    public MensagemCabecalho(boolean publico, Date dataCadastro, boolean ativo) {
        this.publico = publico;
        this.dataCadastro = dataCadastro;
        this.ativo = ativo;
    }

    public MensagemCabecalho(Integer idExercicioClasseMarcacao, boolean publico, Date dataCadastro, boolean ativo) {
        this.idExercicioClasseMarcacao = idExercicioClasseMarcacao;
        this.publico = publico;
        this.dataCadastro = dataCadastro;
        this.ativo = ativo;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIdExercicioClasseMarcacao() {
        return this.idExercicioClasseMarcacao;
    }

    public void setIdExercicioClasseMarcacao(Integer idExercicioClasseMarcacao) {
        this.idExercicioClasseMarcacao = idExercicioClasseMarcacao;
    }

    public Integer getIdExercicioSolucaoClasseMarcacao() {
        return this.idExercicioSolucaoClasseMarcacao;
    }

    public void setIdExercicioSolucaoClasseMarcacao(Integer idExercicioSolucaoClasseMarcacao) {
        this.idExercicioSolucaoClasseMarcacao = idExercicioSolucaoClasseMarcacao;
    }

    public boolean isPublico() {
        return this.publico;
    }

    public void setPublico(boolean publico) {
        this.publico = publico;
    }

    public Date getDataCadastro() {
        return this.dataCadastro;
    }

    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }

    public boolean isAtivo() {
        return this.ativo;
    }

    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
}
