package feeper.Data.entity;
// Generated Feb 1, 2014 9:45:43 AM by Hibernate Tools 3.2.1.GA



/**
 * PessoaConquista generated by hbm2java
 */
public class PessoaConquista  implements java.io.Serializable {


     private Integer id;
     private int idPessoa;
     private int idConquista;
     private String dataConquista;

    public PessoaConquista() {
    }

    public PessoaConquista(int idPessoa, int idConquista, String dataConquista) {
       this.idPessoa = idPessoa;
       this.idConquista = idConquista;
       this.dataConquista = dataConquista;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(int idPessoa) {
        this.idPessoa = idPessoa;
    }
    public int getIdConquista() {
        return this.idConquista;
    }
    
    public void setIdConquista(int idConquista) {
        this.idConquista = idConquista;
    }
    public String getDataConquista() {
        return this.dataConquista;
    }
    
    public void setDataConquista(String dataConquista) {
        this.dataConquista = dataConquista;
    }




}


