package feeper.Data.entity;
// Generated Feb 1, 2014 9:45:43 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.List;


/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


    private Integer id;
    private String nome;
    private String email;
    private String senha;
    private Date dataCadastro;
    private Date dataUltimoAcesso;
    private boolean ativo;
    private boolean gamificado;
    private boolean possuiFoto;
    private int idPerfil;
    private int idTurmaSelecionada;
    private List<Turma> turmas;
    
    private Integer pontos = null;
    private Integer newPontos = null;
    
    private boolean elementoPonto;
    private boolean elementoRanking;
    private boolean elementoMedalha;

    
    
    public boolean isElementoPonto() {
        return elementoPonto;
    }

    public void setElementoPonto(boolean elementoPonto) {
        this.elementoPonto = elementoPonto;
    }

    public boolean isElementoRanking() {
        return elementoRanking;
    }

    public void setElementoRanking(boolean elementoRanking) {
        this.elementoRanking = elementoRanking;
    }

    public boolean isElementoMedalha() {
        return elementoMedalha;
    }

    public void setElementoMedalha(boolean elementoMedalha) {
        this.elementoMedalha = elementoMedalha;
    }
    
    //private List<Turma> turmasProfessor;


    public Pessoa() {
    }

    public Integer getPontos() {
        return pontos;
    }

    public Integer getNewPontos() {
        return newPontos;
    }

    
	
    public Pessoa(String nome, String email, String senha, Date dataCadastro, boolean ativo) {
        this.nome = nome;
        this.email = email;
        this.senha = senha;
        this.dataCadastro = dataCadastro;
        this.ativo = ativo;
    }
    public Pessoa(String nome, String email, String senha, Date dataCadastro, Date dataUltimoAcesso, boolean ativo) {
       this.nome = nome;
       this.email = email;
       this.senha = senha;
       this.dataCadastro = dataCadastro;
       this.dataUltimoAcesso = dataUltimoAcesso;
       this.ativo = ativo;
    }
   
    public Integer getId() {
        return this.id;
    }

    public void setNewPontos(Integer newPontos) {
        this.newPontos = newPontos;
    }

    public void setPontos(Integer pontos) {
        this.pontos = pontos;
    }

    public void setGamificado(boolean gamificado) {
        this.gamificado = gamificado;
    }

    public boolean isGamificado() {
        return gamificado;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Date getDataUltimoAcesso() {
        return this.dataUltimoAcesso;
    }
    
    public void setDataUltimoAcesso(Date dataUltimoAcesso) {
        this.dataUltimoAcesso = dataUltimoAcesso;
    }

    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
    
    public List<Turma> getTurmas() {
        return turmas;
    }

    public void setTurmas(List<Turma> turmas) {
        this.turmas = turmas;
    }

    public int getIdPerfil() {
        return idPerfil;
    }

    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }

    public boolean isPossuiFoto() {
        return possuiFoto;
    }

    public void setPossuiFoto(boolean possuiFoto) {
        this.possuiFoto = possuiFoto;
    }

    public int getIdTurmaSelecionada() {
        return idTurmaSelecionada;
    }

    public void setIdTurmaSelecionada(int idTurmaSelecionada) {
        this.idTurmaSelecionada = idTurmaSelecionada;
    }
    
}
