package feeper.Data.entity;

import java.math.BigDecimal;


/**
 * Exercicio generated by hbm2java
 */
public class Ranking implements java.io.Serializable {

    private Integer id;
    private BigDecimal pontos;
    private int posicao;
    private Pessoa pessoa;
    
    public Ranking() {
    }

    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    public void setPosicao(int posicao) {
        this.posicao = posicao;
    }

    public int getPosicao() {
        return posicao;
    }

    
    public Pessoa getPessoa() {
        return pessoa;
    }

    
    
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setPontos(BigDecimal pontos) {
        this.pontos = pontos;
    }

    public BigDecimal getPontos() {
        return pontos;
    }

   
    
    

    
    
}
