package feeper.Data.entity;
// Generated Feb 8, 2014 11:15:29 PM by Hibernate Tools 3.2.1.GA


/**
 * RespostaCodigoFonte generated by hbm2java
 */
public class RespostaCodigoFonte  implements java.io.Serializable {


     private Integer id;
     private int idResposta;
     private String classe;
     private String fonte;
     private boolean principal;

    public RespostaCodigoFonte() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getIdResposta() {
        return idResposta;
    }

    public void setIdResposta(int idResposta) {
        this.idResposta = idResposta;
    }

    public String getClasse() {
        return classe;
    }

    public void setClasse(String classe) {
        this.classe = classe;
    }

    public String getFonte() {
        return fonte;
    }

    public void setFonte(String fonte) {
        this.fonte = fonte;
    }

    public boolean isPrincipal() {
        return principal;
    }

    public void setPrincipal(boolean principal) {
        this.principal = principal;
    }

}


