package feeper.Data.entity;
// Generated Feb 4, 2014 10:16:34 PM by Hibernate Tools 3.2.1.GA



/**
 * TelaPerfil generated by hbm2java
 */
public class TelaPerfil  implements java.io.Serializable {


     private Integer id;
     private int idTela;
     private int idPerfil;

    public TelaPerfil() {
    }

    public TelaPerfil(int idTela, int idPerfil) {
       this.idTela = idTela;
       this.idPerfil = idPerfil;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdTela() {
        return this.idTela;
    }
    
    public void setIdTela(int idTela) {
        this.idTela = idTela;
    }
    public int getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }




}


