package feeper.Data.entity;
// Generated Feb 1, 2014 9:45:43 AM by Hibernate Tools 3.2.1.GA



/**
 * TurmaPessoaId generated by hbm2java
 */
public class TurmaPessoaId  implements java.io.Serializable {


     private int idTurma;
     private int idPessoa;

    public TurmaPessoaId() {
    }

    public TurmaPessoaId(int idTurma, int idPessoa) {
       this.idTurma = idTurma;
       this.idPessoa = idPessoa;
    }
   
    public int getIdTurma() {
        return this.idTurma;
    }
    
    public void setIdTurma(int idTurma) {
        this.idTurma = idTurma;
    }
    public int getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(int idPessoa) {
        this.idPessoa = idPessoa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TurmaPessoaId) ) return false;
		 TurmaPessoaId castOther = ( TurmaPessoaId ) other; 
         
		 return (this.getIdTurma()==castOther.getIdTurma())
 && (this.getIdPessoa()==castOther.getIdPessoa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTurma();
         result = 37 * result + this.getIdPessoa();
         return result;
   }   


}


